# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import service_pb2 as service__pb2


GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CalculateStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SquareNumber = channel.unary_unary(
                '/service.Calculate/SquareNumber',
                request_serializer=service__pb2.NumberRequest.SerializeToString,
                response_deserializer=service__pb2.NumberReply.FromString,
                _registered_method=True)
        self.AddNumbers = channel.unary_unary(
                '/service.Calculate/AddNumbers',
                request_serializer=service__pb2.AddRequest.SerializeToString,
                response_deserializer=service__pb2.NumberReply.FromString,
                _registered_method=True)


class CalculateServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SquareNumber(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddNumbers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculateServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SquareNumber': grpc.unary_unary_rpc_method_handler(
                    servicer.SquareNumber,
                    request_deserializer=service__pb2.NumberRequest.FromString,
                    response_serializer=service__pb2.NumberReply.SerializeToString,
            ),
            'AddNumbers': grpc.unary_unary_rpc_method_handler(
                    servicer.AddNumbers,
                    request_deserializer=service__pb2.AddRequest.FromString,
                    response_serializer=service__pb2.NumberReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'service.Calculate', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('service.Calculate', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Calculate(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SquareNumber(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/service.Calculate/SquareNumber',
            service__pb2.NumberRequest.SerializeToString,
            service__pb2.NumberReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddNumbers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/service.Calculate/AddNumbers',
            service__pb2.AddRequest.SerializeToString,
            service__pb2.NumberReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
